name = "Skimmer"
version = "0.1.0"
defaultTargets = ["Skimmer", "write_edits"]

[[lean_lib]]
name = "Skimmer"

[[lean_lib]]
name = "SkimmerTest"

[[lean_exe]]
name = "write_edits"
root = "Skimmer.Execute"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"
