name = "Skimmer"
version = "0.1.0"
defaultTargets = ["Skimmer", "SkimmerTest", "write_edits"]

[[lean_lib]]
name = "Skimmer"
leanOptions = { experimental.module = true }

[[lean_lib]]
name = "SkimmerTest"
leanOptions = { experimental.module = true }
globs = ["SkimmerTest.+"]

[[lean_lib]]
name = "SkimmerExtra"
leanOptions = { experimental.module = true }
globs = ["SkimmerExtra.+"]

[[lean_exe]]
name = "write_edits"
root = "Skimmer.Execute"
leanOptions = { experimental.module = true }

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"
